# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doDilation2 <- function(npts, d, nRow, nCol, yul, xll, cellSize, ptRows, ptCols, dist_km) {
    .Call('_fitMaxnet_doDilation2', PACKAGE = 'fitMaxnet', npts, d, nRow, nCol, yul, xll, cellSize, ptRows, ptCols, dist_km)
}

endLatLongC <- function(dist_km, bearing, lat1, long1, isRadians) {
    .Call('_fitMaxnet_endLatLongC', PACKAGE = 'fitMaxnet', dist_km, bearing, lat1, long1, isRadians)
}

